export const budgetSubCategories = {
  Housing: [
    'Rent',
    'mortgage',
    'Home Maintenance/Repairs',
    'Property taxes',
    "Homeowner's insurance",
  ],
  Utilities: ['Electricity', 'Gas', 'Water', 'Internet', 'Phone'],
  Food: ['Groceries', 'Dining Out', 'Snacks/Beverages'],
  Transportation: [
    'Car payment',
    'insurance',
    'Gas/Fuel',
    'Public Transportation',
    'Vehicle Maintenance/Repairs',
    'Car Insurance',
    'Parking/Tolls',
  ],
  'Health and Medical': [
    'Health Insurance',
    'Doctor Visits',
    'Dental Care',
    'Medications/Prescriptions',
    'Vision Care',
  ],
  'Debt Payments': [
    'Credit card payments',
    'Student loans',
    'personal loans',
    'Other Debts',
  ],
  'Savings and Investments': [
    'Emergency Fund',
    'Retirement Savings (401k, IRA)',
    'Education Savings',
    'Investment Accounts',
  ],
  'Personal Care': [
    'Haircuts',
    'toiletries',
    'cosmetics',
    'Clothes',
    'shoes',
    'accessories',
  ],
  Subscriptions: [
    'Streaming services',
    'gym memberships',
    'magazine subscriptions',
  ],
  Entertainment: ['Movies', 'concerts', 'hobbies'],
  'Household Supplies': ['Cleaning products', 'paper products'],
  'Gifts and Donations': [
    'Gifts for Birthdays/Holidays',
    'Tithing/Religious Contributions',
    'charitable contributions',
  ],
  Education: ['Tuition/School Fees', 'Books/Supplies', 'Online Courses'],
  Miscellaneous: ['Pet expenses', 'travel', 'unexpected costs'],
  'Emergency Fund': ['Savings for unexpected expenses'],
  'Retirement Savings': ['401(k)', 'IRA'],
  'Goal-Based Savings': [
    'Savings for specific goals like a down payment',
    'vacation',
    'education',
  ],
};

export const budgetCategory = [
  'Debt Payments',
  'Housing',
  'Subscriptions',
  'Transportation',
  'Utilities',
  'Entertainment',
  'Education',
  'Food',
  'Gifts and Donations',
  'Health and Medical',
  'Household Supplies',
  'Miscellaneous',
  'Personal Care',
  'Emergency',
  'Goal-Based Savings',
  'Savings and Investments',
  'Retirement Savings',
];
export const budgetType = ['Fixed', 'Variable', 'Saving & Investment'];

export const budgetData: BudgetProps[] = [
  {
    amount: 5200,
    createdAt: 'Sept 1, 2024',
    spent: 0,
    type: 'Fixed',
    category: 'Personal Care',
    completedAt: 'Sept 15, 2024',
    expiredOn: '30th Sept, 2024',
    status: 'active',
    subCategory: 'Charitable contributions',
    month: 'September',
    year: '2024',
  },
  {
    amount: 4200,
    createdAt: 'Sept 1, 2024',
    spent: 500,
    type: 'Variable',
    category: 'Housing',
    completedAt: 'Sept 15, 2024',
    expiredOn: '30th Sept, 2024',
    status: 'pending',
    subCategory: 'Rent',
    month: 'September',
    year: '2024',
  },
  {
    amount: 1200,
    createdAt: 'Sept 1, 2024',
    spent: 500,
    type: 'Saving & Investment',
    category: 'Debt Payments',
    completedAt: 'Sept 15, 2024',
    expiredOn: '30th Sept, 2024',
    status: 'completed',
    subCategory: 'Rent',
    month: 'September',
    year: '2024',
  },
];
